# @get all products
GET http://localhost:4000/api/products/

###

# @create product
POST http://localhost:4000/api/products/
content-type : application/json

{
    "name":"hung",
    "price":12,
    "description":"mo ta abc",
    "image":"hung.jpg",
    "shipping":true
}

###

# @delete product
DELETE http://localhost:4000/api/products/60545d2982600724e46d6d66

###

# @update product
PUT http://localhost:4000/api/products/60545d2a82600724e46d6d67
content-type : application/json

{
    "name":"hung update",
    "price":12,
    "description":"mo ta update",
    "image":"hung.jpg",
    "shipping":false
}